home:
	stow --verbose --target=$$HOME --restow i3/
	stow --verbose --target=$$HOME --restow i3status/
	stow --verbose --target=$$HOME --restow nvim/
	stow --verbose --target=$$HOME --restow zsh/

work:
	stow --verbose --target=$$HOME --restow i3/
	stow --verbose --target=$$HOME --restow i3status/
	stow --verbose --target=$$HOME --restow nvim/
	stow --verbose --target=$$HOME --restow zsh/

clean:
	stow --verbose --target=$$HOME --delete */
