- name: Setup Fedora Developer Workstation
  hosts: all
  pre_tasks:
    - name: update dnf
      dnf:
        update_cache: true
        update_only: true
        state: present
  tasks:
    - name: Global Tasks
      include_tasks: 
        file: "{{ file }}"
        apply:
          tags:
            - always
      loop:    
        - tasks/development.yaml
        - tasks/infrastructure.yaml
        - tasks/stow.yaml
        - tasks/rust.yaml
        - tasks/vscode.yaml
        - tasks/zsh.yaml
      loop_control:
        loop_var: file
      tags:
        - always
    
    - name: Home / Work Tasks
      include_tasks: "{{ file }}"
      loop:
        - tasks/git.yaml
        - tasks/projects.yaml
      loop_control:
        loop_var: file
      tags: 
        - home
        - work
        - never
