- name: Setup Fedora Developer Workstation
  hosts: all
  pre_tasks:
    - name: Update all dnf packages
      dnf:
        name: "*"
        state: latest
  tasks:
    - name: Global Tasks
      include_tasks: 
        file: "{{ file }}"
        apply:
          tags:
            - always
      loop:    
        - tasks/tools.yaml
        - tasks/languages.yaml
        - tasks/rust.yaml
        - tasks/kernel.yaml
        - tasks/stow.yaml
      loop_control:
        loop_var: file
      tags:
        - always

