- name: Ensure Ansible is installed
  dnf:
    name: ansible
    state: latest

- name: Ensure Python is installed
  dnf:
    name: python
    state: latest
    
- name: Ensure Git is installed
  dnf:
    name: git
    state: latest