- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "erickrenz"

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "krenz.eric.krenz@gmail.com"
