- name: Install i3 and tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    # i3wm
    - i3
    - i3status
    - i3lock
    - dmenu
    - feh
    # popos/shell
    - gnome-shell-extension-pop-shell
    - xprop
