- name: Install i3 and tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    # Default
    - i3
    - i3status
    - i3lock
    - dmenu
    - feh
    # Custom
    - xfce4-terminal
    - kitty
    - alacritty
    - tmux
    - jetbrains-mono-fonts-all

- name: Install Neovim
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - python3-neovim
    - ripgrep

- name: Install miscelaneous utilities
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - podman 
    - neofetch 
    - cmatrix 
    - wget  
    - openssh-server
    - wireguard-tools
    - stow
    - gh
    - git-crypt
    - direnv

- name: Stow dotfiles - Home
  shell: make -C /home/ekrenz/.dotfiles/dotfiles

- name: Create a directory if it does not exist
  file:
    path: "/home/ekrenz/code"
    state: directory
    owner: ekrenz
  tags:
    - always
