- name: Install Neovim and Bash tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - foot
    - tmux
    - fzf
    - jetbrains-mono-fonts-all
    - neovim
    - python3-neovim
    - ripgrep

- name: Install miscelaneous utilities
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - podman 
    - neofetch 
    - cmatrix 
    - wget  
    - openssh-server
    - wireguard-tools
    - stow
    - gh
    - git-crypt
    - direnv
    - util-linux-user

- name: Enable copr for starship
  community.general.copr:
    name: atim/starship

- name: Install starship
  dnf:
    name: "starship"
    state: latest

- name: Stow dotfiles - Home
  shell: make -C /home/ekrenz/.dotfiles/dotfiles

- name: Create a directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ekrenz
  loop:
    - /home/ekrenz/code
    - /home/ekrenz/kernel
