- name: Enable Neovim
  community.general.copr:
    name: agriffis/neovim-nightly

- name: Install Neovim
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - python3-neovim
    - ripgrep