- name: Create a directory if it does not exist
  file:
    path: "/home/ekrenz/code"
    state: directory
    owner: ekrenz
- name: personal website
  git:
    repo: "https://github.com/erickrenz/ekrenz.com.git" 
    dest: "/home/ekrenz/code/ekrenz.com/"
- name: learn rust
  git:
    repo: "https://github.com/erickrenz/learn-rust.git"
    dest: "/home/ekrenz/code/learn-rust/"
