- name: See if rustup exists
  stat:
    path: ~/.cargo/bin/rustup
  register: rustup_stats

- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  when: rustup_stats.stat.exists == False

- name: source rustup
  shell: source "$HOME/.cargo/env"
  when: rustup_stats.stat.exists == False