- name: Enable copr for starship
  community.general.copr:
    name: atim/starship

- name: Install Neovim and Bash tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    # Sway 
    - sway
    - foot
    - tmux
    - fzf
    - jetbrains-mono-fonts-all
    # Neovim
    - neovim
    - python3-neovim
    - ripgrep
    # Bash Utils
    - podman 
    - stow
    - ansible
    - git
    - gh
    - jq
    - parallel
    - starship
    - neofetch 
    - cmatrix 
    - wget  
    - openssh-server
    - wireguard-tools
    - git-crypt
    - direnv
    - util-linux-user
