- name: Install miscelaneous utilities
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - podman 
    - neofetch 
    - wget  
    - openssh-server
    - i3
    - i3status
    - i3lock
    - dmenu
    - feh

