- name: Install miscelaneous utilities
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - podman 
    - neofetch 
    - cmatrix 
    - wget  
    - openssh-server
    - stow
    - tmux
    - gh
