- name: See if rustup exists
  stat:
    path: /Users/erickrenz/.cargo/bin/rustup
  register: rustup_stats

- name: Install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "/Users/erickrenz/.cargo/env"
  when: rustup_stats.stat.exists == False
  become_user: erickrenz
