- name: Install programming languages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    # Install groups are the "build-essential" equivalent for Fedora
    - '@Development Tools'
    - '@C Development Tools and Libraries'
    # LLVM and Clang
    # https://packages.fedoraproject.org/pkgs/llvm/llvm/
    - llvm 
    - clang 
    - cmake 
    - lld
    - lldb 
    - clang-tools-extra
    # Node
    - nodejs
    - npm
    # Python
    - python
    - python3-pip
    - python3-wheel
    - python3-devel
    - python3-virtualenv
    # Go
    - golang
    # Lua
    - lua
    - luarocks
    # nvim checkhealth
    - ruby
    - java
    - julia
    - perl
    - php
    - composer

- name: Install asdf prerequisites
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - git

- name: See if asdf exists
  stat:
    path: /home/ekrenz/.asdf
  register: asdf_stats

- name: Install asdf
  shell: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.1
  when: asdf_stats.stat.exists == False
  become_user: ekrenz

